
# resume information
resume-index = 653885
seed = 10820376724740460611
rate = 100       
shard = 1/1
nocapture = servername
nocapture = servername

output-filename = masscanu.xml
output-format = xml

adapter-ip = 172.16.1.141
# TARGET SELECTION (IP, PORTS, EXCLUDES)
ports = U:0-5000
range = 31.156.174.0/24
