
# resume information
resume-index = 99255
seed = 14697671269609299560
rate = 100       
shard = 1/1
nocapture = servername
nocapture = servername


adapter-ip = 172.16.1.141
# TARGET SELECTION (IP, PORTS, EXCLUDES)
ports = 0-5000
range = 31.156.174.0/24
